<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Model_karyawan extends CI_Model
{

    public $table = 'karyawan';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select('karyawan.*, perusahaan.*');
        $this->db->join('perusahaan', 'perusahaan.kode = karyawan.kode_pt', 'left');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('karyawan.*, perusahaan.nama');
        $this->db->join('perusahaan', 'perusahaan.kode = karyawan.kode_pt', 'left');
        $this->db->where($this->table . '.' . $this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->select('karyawan.id,karyawan.nama_lengkap, perusahaan.nama, karyawan_gaji.variabel_id, karyawan_gaji.nominal');
        $this->db->join('perusahaan', 'perusahaan.kode = karyawan.kode_pt', 'left');
        $this->db->join('karyawan_gaji', 'karyawan_gaji.karyawan_id = karyawan.id', 'left');
        $this->db->like('karyawan.id', $q);
        $this->db->or_like('perusahaan.nama', $q);
        $this->db->or_like('karyawan.nama_lengkap', $q);
        $this->db->from($this->table);
        $this->db->group_by('karyawan.id');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->select('karyawan.id, karyawan.nama_lengkap, perusahaan.nama, karyawan_gaji.variabel_id, karyawan_gaji.nominal');
        $this->db->join('perusahaan', 'perusahaan.kode = karyawan.kode_pt', 'left');
        $this->db->join('karyawan_gaji', 'karyawan_gaji.karyawan_id = karyawan.id', 'left');
        $this->db->like('karyawan.id', $q);
        $this->db->or_like('perusahaan.nama', $q);
        $this->db->or_like('karyawan.nama_lengkap', $q);
        $this->db->group_by('karyawan.id');
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    //get relation setting gaji
    function relation_gaji()
    {
        $this->db->select('karyawan.id, karyawan.nama_lengkap, perusahaan.nama, karyawan_gaji.variabel_id, karyawan_gaji.nominal');
        $this->db->join('perusahaan', 'perusahaan.kode = karyawan.kode_pt', 'left');
        $this->db->join('karyawan_gaji', 'karyawan_gaji.karyawan_id = karyawan.id', 'left');
        $this->db->group_by('karyawan.id');
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Model_karyawan.php */
/* Location: ./application/models/Model_karyawan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-01-25 03:45:32 */
/* http://harviacode.com */